// Generated by CoffeeScript 1.7.1
(function() {
  describe('Calculator', function() {
    it('can add two positive numbers', function() {
      var calculator, result;
      calculator = new Calculator();
      result = calculator.add(2, 3);
      return expect(result).toBe(5);
    });
    it('can handle negative number addition', function() {
      var calculator, result;
      calculator = new Calculator();
      result = calculator.add(-10, 5);
      return expect(result).toBe(-5);
    });
    it('can subtract two positive numbers', function() {
      var calculator, result;
      calculator = new Calculator();
      result = calculator.subtract(10, 6);
      return expect(result).toBe(4);
    });
    return it('can handle negative number subtraction', function() {
      var calculator, result;
      calculator = new Calculator();
      result = calculator.subtract(4, -6);
      return expect(result).toBe(10);
    });
  });

}).call(this);
