// Generated by CoffeeScript 1.7.1
var Calculator;

window.Calculator = Calculator = (function() {
  function Calculator() {}

  Calculator.prototype.add = function(a, b) {
    return a + b;
  };

  Calculator.prototype.subtract = function(a, b) {
    return a - b;
  };

  return Calculator;

})();
